hunt = {
    'green pencil': 'in the pencil holder on the desk',
    'red book': 'on the bookshelf',
    'blue pen': 'in the drawer of the desk',
    'horse figurine':'on top of the buffet',
    'baseball': 'in the backyard',
    'plaid socks': 'under the dryer',
    'ficus plant': 'in the bedroom on the window sill',
    'deck of cards': 'in the junk drawer',
    'green marble': 'in the toy trunk',
    'bluejay bird': 'in the tree in the front yard',
    'orange tabby': 'in Judy\'s garden accross the street',
    'purple ten speed bike': 'chained outside the corner store',
    'cloisonne vase': 'on the dresser in the pink room',
    'black tray': 'under the bed',
    'hairbrush': 'in the closet',
    'yellow soap dish': 'under the ficus plant',
    'diary': 'under the mattress',
}